Repository aqerd/filmbot, pull requests merged in 2024-11, with the labels that each got.

#13 Adding tests
  pom.xml
  src/main/java/org/oopproject/SiteRequests.java
  src/main/java/org/oopproject/TelegramBot.java
  src/main/java/org/oopproject/utils/Genres.java
  src/main/java/org/oopproject/utils/Replies.java
  src/test/java/org/oopproject/HandleAgeTest.java
  src/test/java/org/oopproject/HandleCommandsTest.java
  src/test/java/org/oopproject/HandleGenreTest.java
  src/test/java/org/oopproject/HandleYearTest.java
  src/test/java/org/oopproject/MainTest.java
  src/test/java/org/oopproject/ValidatorsTest.java
Labels: enhancement

#14 Added Github actions support
  .github/workflows/maven.yml
Labels: enhancement

#15 Storing-expectations-for-commands-in-new-enum
  src/main/java/org/oopproject/Main.java
  src/main/java/org/oopproject/TelegramBot.java
  src/main/java/org/oopproject/utils/CommandWaiter.java
Labels: enhancement, done

#50 added sendler message for subscribed users. Added saving and getting …
  src/main/java/org/oopproject/Database.java
  src/main/java/org/oopproject/TelegramBot.java
  src/main/java/org/oopproject/utils/CommandWaiter.java
  src/main/java/org/oopproject/utils/Replies.java
  src/main/java/org/oopproject/utils/Validators.java
Labels: enhancement, done

#49 New tests
  src/main/java/org/oopproject/Main.java
  src/main/java/org/oopproject/SiteRequests.java
  src/main/java/org/oopproject/TelegramBot.java
  src/main/java/org/oopproject/deserializers/FilmDeserializer.java
  src/main/java/org/oopproject/deserializers/ListDeserializer.java
  src/main/java/org/oopproject/deserializers/PersonDeserializer.java
  src/main/java/org/oopproject/utils/CommandWaiter.java
  src/main/java/org/oopproject/utils/Config.java
  src/main/java/org/oopproject/utils/Replies.java
  src/main/java/org/oopproject/utils/Validators.java
  src/test/java/org/oopproject/HandleCommandsTest.java
  src/test/java/org/oopproject/HandleGenreTest.java
  src/test/java/org/oopproject/HandleSetAgeTest.java
  src/test/java/org/oopproject/MainTest.java
  src/test/java/org/oopproject/RequestsCheckTest.java
  src/test/java/org/oopproject/ValidatorsTest.java
Labels: enhancement, done

#51 New requests
  src/main/java/org/oopproject/SiteRequests.java
  src/main/java/org/oopproject/TelegramBot.java
  src/main/java/org/oopproject/deserializers/CreditsDeserializer.java
  src/main/java/org/oopproject/deserializers/DateDeserializer.java
  src/main/java/org/oopproject/deserializers/ListDeserializer.java
  src/main/java/org/oopproject/deserializers/PersonDeserializer.java
  src/main/java/org/oopproject/utils/Replies.java
  src/main/java/org/oopproject/utils/Validators.java
  src/test/java/org/oopproject/RequestsCheckTest.java
Labels: enhancement, done

#52 Trailer support
  src/main/java/oop/project/SiteRequests.java
  src/main/java/oop/project/TelegramBot.java
  src/main/java/oop/project/deserializers/ListDeserializer.java
  src/main/java/oop/project/deserializers/VideoDeserializer.java
  src/main/java/oop/project/shared/Config.java
  src/test/java/oop/project/RequestsCheckTest.java
Labels: enhancement, done

#57 Code enhancement
  src/main/java/oop/project/Database.java
  src/main/java/oop/project/Main.java
  src/main/java/oop/project/MovieParameters.java
  src/main/java/oop/project/SiteRequests.java
  src/main/java/oop/project/TelegramBot.java
  src/main/java/oop/project/deserializers/AuthDeserializer.java
  src/main/java/oop/project/deserializers/CreditsDeserializer.java
  src/main/java/oop/project/deserializers/FilmDeserializer.java
  src/main/java/oop/project/deserializers/GenreDeserializer.java
  src/main/java/oop/project/deserializers/LanguageDeserializer.java
  src/main/java/oop/project/deserializers/ListDeserializer.java
  src/main/java/oop/project/deserializers/PersonDeserializer.java
  src/main/java/oop/project/deserializers/VideoDeserializer.java
  src/main/java/oop/project/handlers/Buttons.java
  src/main/java/oop/project/handlers/Commands.java
  src/main/java/oop/project/handlers/Keyboards.java
  src/main/java/oop/project/parameters/MovieParameters.java
  src/main/java/oop/project/parameters/ParametersBuilder.java
  src/main/java/oop/project/shared/AgeRating.java
  src/main/java/oop/project/shared/Config.java
  src/main/java/oop/project/shared/Genres.java
  src/main/java/oop/project/shared/Replies.java
  src/main/java/oop/project/shared/Responses.java
  src/main/java/oop/project/shared/Utils.java
  src/main/java/oop/project/validators/CommandValidator.java
  src/main/java/oop/project/validators/Validator.java
  src/test/java/oop/project/HandleCommandsTest.java
  src/test/java/oop/project/KeyboardsTest.java
  src/test/java/oop/project/RequestsCheckTest.java
  src/test/java/oop/project/UtilsTest.java
  src/test/java/oop/project/commands/BaseHandleTest.java
  src/test/java/oop/project/commands/HandleCommandsTest.java
  src/test/java/oop/project/commands/HandleFindByIdTest.java
  src/test/java/oop/project/commands/HandleGenreTest.java
  src/test/java/oop/project/commands/HandleSetAgeTest.java
  src/test/java/oop/project/commands/HandleYearTest.java
Labels: bug, enhancement, done, skill issue
